#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#
# 2020.11.25 - Created to adjust r710 fan speed on boot
ipmitool -H 192.168.1.120 -I lanplus -U root -P A7hqKsBU raw 0x30 0x30 0x01 0x00
ipmitool -H 192.168.1.120 -I lanplus -U root -P A7hqKsBU raw 0x30 0x30 0x02 0xff 0x07